const GET_PRODUCTS_PENDING = "GET_PRODUCTS_PENDING";

const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";

const GET_PRODUCTS_FAILED = "GET_PRODUCTS_FAILED";
const SET_SEARCH_FIELD = "SET_SEARCH_FIELD";
export {
  GET_PRODUCTS_FAILED,
  GET_PRODUCTS_PENDING,
  GET_PRODUCTS_SUCCESS,
  SET_SEARCH_FIELD,
};
