const GET_PRODUCTS_PENDING = "GET_PRODUCTS_PENDING";

const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";

const GET_PRODUCTS_FAILED = "GET_PRODUCTS_FAILED";

export { GET_PRODUCTS_FAILED, GET_PRODUCTS_PENDING, GET_PRODUCTS_SUCCESS };
