const GET_PRODUCTS_PENDING = "GET_PRODUCTS_PENDING";

const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";

const GET_PRODUCTS_FAILED = "GET_PRODUCTS_FAILED";
const SET_SEARCH_FIELD = "SET_SEARCH_FIELD";

const GET_USER_PENDING = "GET_USER_PENDING";
const GET_USER_SUCCESS = "GET_USER_SUCCESS";
const GET_USER_FAILED = "GET_USER_FAILED";
export {
  GET_PRODUCTS_FAILED,
  GET_PRODUCTS_PENDING,
  GET_PRODUCTS_SUCCESS,
  SET_SEARCH_FIELD,
  GET_USER_PENDING,
  GET_USER_SUCCESS,
  GET_USER_FAILED,
};
